---
# tasks file for terraform
- name: install apt-packages
  apt: name={{ item }} state=installed
  with_items:
    - python3
    - python3-pip 
    - ipython3 
    - ipython3-notebook

- name: install pip
  shell: curl https://bootstrap.pypa.io/get-pip.py | python3
  args:
    creates: /usr/local/bin/pip

- name: install PyTFE-Core
  pip: 
    executable: /usr/local/bin/pip
    name: tfe

- name: install tfe-backup
  pip:
    executable: /usr/local/bin/pip
    name: tfe-backup


- name: download binaries
  when: install == "enterprise"
  unarchive: 
    src: "{{ download_url }}" 
    dest: /usr/local/bin
    remote_src: true

  